### ISSUE TITLE
Why checking JWT issuer, audience and expiration AFTER cryto operations

### ISSUE THREAD

**Issue by pleothaud** [ermites-io/oidc#1]
JWT issuer, audience and expiration verification happens ONLY after JWT sig validation.

IMHO there is no need to engage heavy crypto operations if JWT issuer, audience and expiration are not valid.

WDYT?

**Comment by eau-u4f** [comment]
because you don't operate on unauthenticated data, first authenticate, then process, if it is (authenticated), you can operate on data within, as described in the README.
